mesh: "path/to/input/mesh.obj"
path_rgba: "path/to/input/rgba.png"
outdir: "path/to/output/directory"
enhance: true # whether NeTF enhancement is used

prompt: "reconstruction prompt"
positive_prompt: "high fidelity, best quality, clean surface with necessary shadow, extremely detailed, masterpiece, high resolution, high quality, realistic"
negative_prompt: "ugly, bad anatomy, blurry, pixelated obscure, unnatural colors, poor lighting, dull, unclear, cropped, lowres, low quality, artifacts, duplicate, morbid, mutilated, poorly drawn face, deformed, dehydrated, bad proportions, unfocused"

text_dir: false
front_dir: "+x"

iters: 200

# training resolution
render_resolution: 512

# training camera parameters
radius: 5.0
fovy: 49.1


fix_geo: true
mix_normal: false
fit_tex: true
fit_tex_iters: 600


mode: "SD" # ['SD', 'IF2']
tex_mode: "hashgrid" # ['hashgrid', 'mlp', 'triplane']


batch_size: 1
batch_size_train: 4
t5_iters: -1


env_texture: null
env_scale: 2.0


remesh_interval: 200
decimate_target: 50000
remesh_size: 0.015
texture_resolution: 1024

hashgrid_lr: 0.01
mlp_lr: 0.001
unet_lr: 0.0001

# VSD
vds: true
q_cond: true
v_pred: true
K: 1
K2: 1
unet_bs: 1
uncond_p: 0.1

# guidance loss weights
lambda_sd: 1.0


force_cuda_rast: true
vram_O: false

reconstruction_picked_views: [
  111, 115, 120, 125, 129, 133, 138, 143,
  148, 152, 157, 162, 166, 170, 175, 180,
  221, 189, 194, 199, 203, 207, 212, 217,
  222, 226, 231, 236, 240, 244, 249, 254,
  259, 263, 268, 273, 277, 281, 286, 291
                              ]