input_dir: ""
output_dir: ""
initial_mesh: ""

enhanced_normal_map_loss: true
optim_only_visible: true
iterations_first: 3000
iterations_second: 1000
upsample_iterations: [3500]

lr_vertices: 0.001

save_frequency: 500
visualization_frequency: 500
visualization_views: []
device: 0

weight_hole_mask: 2.0
weight_mask: 2.0
weight_normal_consistency: 0.1
weight_laplacian: 40.0
weight_normal: 0.8
weight_shading: 1.0


lr_shader: 0.001
shading_percentage: 0.75
hidden_features_layers: 3
hidden_features_size: 256
fourier_features: "positional" # choices=(['none', 'gfft', 'positional'])
activation: "relu" # choices=(['relu', 'sine'])
fft_scale: 4

picked_views_first: [74, 333]
picked_views_second: [
                      111, 115, 120, 125, 129, 133, 138, 143,
                      # 148, 152, 157, 162, 166, 170, 175, 180,
                      221, 189, 194, 199, 203, 207, 212, 217,
                      # 222, 226, 231, 236, 240, 244, 249, 254,
                      259, 263, 268, 273, 277, 281, 286, 291
                  ]